// <auto-generated />
using System;
using Architecture.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Architecture.Migrations
{
    [DbContext(typeof(ArchitectureContext))]
    [Migration("20200817230401_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Architecture.Models.Bridge", b =>
                {
                    b.Property<int>("BridgeId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Architect")
                        .IsRequired();

                    b.Property<string>("City")
                        .IsRequired();

                    b.Property<string>("Country")
                        .IsRequired();

                    b.Property<DateTime>("DateOfConstruction");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("BridgeId");

                    b.ToTable("Bridges");

                    b.HasData(
                        new
                        {
                            BridgeId = 1,
                            Architect = "Joseph Strauss",
                            City = "San Francisco",
                            Country = "USA",
                            DateOfConstruction = new DateTime(1933, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Golden Gate"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
