// <auto-generated />
using System;
using Architecture.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Architecture.Migrations
{
    [DbContext(typeof(ArchitectureContext))]
    [Migration("20200817210614_RemoveReq")]
    partial class RemoveReq
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Architecture.Models.Bridge", b =>
                {
                    b.Property<int>("BridgeId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Architect");

                    b.Property<string>("City");

                    b.Property<string>("Country");

                    b.Property<DateTime>("EndDate");

                    b.Property<int>("Length");

                    b.Property<string>("Name");

                    b.Property<DateTime>("StartDate");

                    b.HasKey("BridgeId");

                    b.ToTable("Bridges");

                    b.HasData(
                        new
                        {
                            BridgeId = 1,
                            Architect = "Joseph Strauss",
                            City = "San Francisco",
                            Country = "USA",
                            EndDate = new DateTime(1937, 4, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Length = 2737,
                            Name = "Golden Gate",
                            StartDate = new DateTime(1933, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BridgeId = 2,
                            Architect = "Dr. Michel Virlogeux",
                            City = "Millau",
                            Country = "France",
                            EndDate = new DateTime(2004, 12, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Length = 2460,
                            Name = "Viaduc de Millau",
                            StartDate = new DateTime(2001, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BridgeId = 3,
                            Architect = "Dorman Long & Co.",
                            City = "Sydney",
                            Country = "Australia",
                            EndDate = new DateTime(1932, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Length = 1149,
                            Name = "Sydney Harbor Bridge",
                            StartDate = new DateTime(1923, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BridgeId = 4,
                            Architect = "Satoshi Kashima",
                            City = "Kobe",
                            Country = "Japan",
                            EndDate = new DateTime(1998, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Length = 3911,
                            Name = "Akashi Kaikyō Bridge",
                            StartDate = new DateTime(1998, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BridgeId = 5,
                            Architect = "Armando Rito",
                            City = "Lisbon",
                            Country = "Portugal",
                            EndDate = new DateTime(1998, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Length = 12345,
                            Name = "Vasco Da Gama Bridge",
                            StartDate = new DateTime(1995, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BridgeId = 6,
                            Architect = "John Augustus Roebling",
                            City = "New York City",
                            Country = "USA",
                            EndDate = new DateTime(1883, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Length = 1834,
                            Name = "Brooklyn Bridge",
                            StartDate = new DateTime(1870, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
